version: "3"

services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - grafana-config:/etc/grafana
      - grafana-data:/var/lib/grafana

volumes:
  grafana-config:
  grafana-data:
