services:
  grafana:
    build: .
    ports:
      - "10004:3000"
    environment:
      - GRAFANA_ENV=${GRAFANA_ENV:-server} # Default to server if not specified
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    user: root
    volumes:
      - grafana-config:/etc/grafana
      - grafana-data:/var/lib/grafana

volumes:
  grafana-config:
  grafana-data:
